### ISSUE TITLE
Deploy.sh падает с ошибкой при запуске контейнера  ./ton-node.

### ISSUE THREAD

**Issue by senitskiy** [tonlabs/TON-OS-DApp-Server#5]
При выполнение скрипта deploy.sh вылетает следущая
**ошибка:**
error: couldn't read catchain/../common/build/build.rs: No such file or directory (os error 2)
error: aborting due to previous error
error: could not compile `catchain`
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
ERROR: Service 'node' failed to build: The command '/bin/sh -c cargo build --release --features "external_db,metrics"' returned a non-zero code: 101

{Почему-то директория: `/TON-OS-DApp-Server/docker-compose/ton-node/build/ton-node/common` не содержит никаких файлов. 
**Решение:**
Выполнил команду: `git submodule update --init` в следующей директории 
`~/TON-OS-DApp-Server/docker-compose/ton-node/build/ton-node#`

В конфигах ton-node до кучи прописал rust 1.49.0. Далее запускал поочерёдно каждый контейнер вручную. В итоге DApp запустился без проблем. До этого пользовался этими скриптами без проблем. Были какие-то изменения, может что-то из них не учитывается в текущих скриптах.

**Comment by huawuque18** [comment]
error: couldn't read catchain/../common/build/build.rs: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `catchain`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
ERROR: Service 'node' failed to build: The command '/bin/sh -c cargo build --release --features "external_db,metrics"' returned a non-zero code: 101



I also made this mistake,
Don't know how to proceed

**Comment by huawuque18** [comment]
> При выполнение скрипта deploy.sh вылетает следущая
> **ошибка:**
> error: couldn't read catchain/../common/build/build.rs: No such file or directory (os error 2)
> error: aborting due to previous error
> error: could not compile `catchain`
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> ERROR: Service 'node' failed to build: The command '/bin/sh -c cargo build --release --features "external_db,metrics"' returned a non-zero code: 101
> 
> {Почему-то директория: `/TON-OS-DApp-Server/docker-compose/ton-node/build/ton-node/common` не содержит никаких файлов.
> **Решение:**
> Выполнил команду: `git submodule update --init` в следующей директории
> `~/TON-OS-DApp-Server/docker-compose/ton-node/build/ton-node#`
> 
> В конфигах ton-node до кучи прописал rust 1.49.0. Далее запускал поочерёдно каждый контейнер вручную. В итоге DApp запустился без проблем. До этого пользовался этими скриптами без проблем. Были какие-то изменения, может что-то из них не учитывается в текущих скриптах.


-----------------------------------------------------------------------------------------
I modified rust 1.49.0
Performed according to your operation and reported this error again! Do you know what's going on?


error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `ton_node`

To learn more, run the command again with --verbose.
ERROR: Service 'node' failed to build: The command '/bin/sh -c cargo build --release --features "external_db,metrics"' returned a non-zero code: 101

**Comment by senitskiy** [comment]
run in console:
~ `cd /TON-OS-DApp-Server/docker-compose/ton-node/build/ton-node`
~ `git submodule update --init`

and try again run script.

**Comment by artemr-tl** [comment]
Fixed, thanks for reporting.
